sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

os:
  - linux

branches:
  only:
  - master

notifications:
  email: false
  irc:
    channels:
    - "chat.freenode.net#rawtherapee"
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  global:
  - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential cmake curl git libbz2-dev libcanberra-gtk-dev libexiv2-dev libexpat-dev libfftw3-dev libglibmm-2.4-dev libgtk2.0-dev libgtkmm-2.4-dev libiptcdata0-dev libjpeg8-dev liblcms2-dev libpng12-dev libsigc++-2.0-dev libtiff5-dev zlib1g-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" -DWITH_LTO="OFF" -DPROC_TARGET_NUMBER="2"

script: make
